-- Synchronize SNAP response code mappings from ASPI Response Code reference.
-- ASPI defines service_code as "any"; this auth-service materializes it as service_code 73.

ALTER TABLE response_code_mappings
  MODIFY description VARCHAR(2000) NULL;

DELETE FROM response_code_mappings
WHERE service_code = '73';

INSERT INTO response_code_mappings
(category, http_status, service_code, case_code, response_code, response_message, description, created_by, updated_by)
VALUES
('SUCCESS', 200, '73', '00', '2007300', 'Successful', 'Successful', 'flyway', 'flyway'),
('SUCCESS', 202, '73', '00', '2027300', 'Request In Progress', 'Transaction still on process', 'flyway', 'flyway'),
('SYSTEM', 400, '73', '00', '4007300', 'Bad Request', 'General request failed error, including message parsing failed.', 'flyway', 'flyway'),
('MESSAGE', 400, '73', '01', '4007301', 'Invalid Field Format {field name}', 'Invalid format', 'flyway', 'flyway'),
('MESSAGE', 400, '73', '02', '4007302', 'Invalid Mandatory Field {field name}', 'Missing or invalid format on mandatory field', 'flyway', 'flyway'),
('SYSTEM', 401, '73', '00', '4017300', 'Unauthorized. [reason]', 'General unauthorized error (No Interface Def, API is Invalid, Oauth Failed, Verify Client Secret Fail, Client Forbidden Access API, Unknown Client, Key not Found)', 'flyway', 'flyway'),
('SYSTEM', 401, '73', '01', '4017301', 'Invalid Token (B2B)', 'Token found in request is invalid (Access Token Not Exist, Access Token Expiry)', 'flyway', 'flyway'),
('SYSTEM', 401, '73', '02', '4017302', 'Invalid Customer Token', 'Token found in request is invalid (Access Token Not Exist, Access Token Expiry)', 'flyway', 'flyway'),
('SYSTEM', 401, '73', '03', '4017303', 'Token Not Found (B2B)', 'Token not found in the system. This occurs on any API that requires token as input parameter', 'flyway', 'flyway'),
('SYSTEM', 401, '73', '04', '4017304', 'Customer Token Not Found', 'Token not found in the system. This occurs on any API that requires token as input parameter', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '00', '4037300', 'Transaction Expired', 'Transaction expired', 'flyway', 'flyway'),
('SYSTEM', 403, '73', '01', '4037301', 'Feature Not Allowed [Reason]', 'This merchant is not allowed to call Direct Debit APIs', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '02', '4037302', 'Exceeds Transaction Amount Limit', 'Exceeds Transaction Amount Limit', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '03', '4037303', 'Suspected Fraud', 'Suspected Fraud', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '04', '4037304', 'Activity Count Limit Exceeded', 'Too many request, Exceeds Transaction Frequency Limit', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '05', '4037305', 'Do Not Honor', 'Account or User status is abnormal', 'flyway', 'flyway'),
('SYSTEM', 403, '73', '06', '4037306', 'Feature Not Allowed At This Time. [reason]', 'Cut off In Progress', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '07', '4037307', 'Card Blocked', 'The payment card is blocked', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '08', '4037308', 'Card Expired', 'The payment card is expired', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '09', '4037309', 'Dormant Account', 'The account is dormant', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '10', '4037310', 'Need To Set Token Limit', 'Need to set token limit', 'flyway', 'flyway'),
('SYSTEM', 403, '73', '11', '4037311', 'OTP Blocked', 'OTP has been blocked', 'flyway', 'flyway'),
('SYSTEM', 403, '73', '12', '4037312', 'OTP Lifetime Expired', 'OTP has been expired', 'flyway', 'flyway'),
('SYSTEM', 403, '73', '13', '4037313', 'OTP Sent To Cardholer', 'initiates request OTP to the issuer', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '14', '4037314', 'Insufficient Funds', 'Insufficient Funds', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '15', '4037315', 'Transaction Not Permitted.[reason]', 'Transaction Not Permitted', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '16', '4037316', 'Suspend Transaction', 'Suspend Transaction', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '17', '4037317', 'Token Limit Exceeded', 'Purchase amount exceeds the token limit set prior', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '18', '4037318', 'Inactive Card/Account/Customer', 'Indicates inactive account', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '19', '4037319', 'Merchant Blacklisted', 'Merchant is suspended from calling any APIs', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '20', '4037320', 'Merchant Limit Exceed', 'Merchant aggregated purchase amount on that day exceeds the agreed limit', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '21', '4037321', 'Set Limit Not Allowed', 'Set limit not allowed on particular token', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '22', '4037322', 'Token Limit Invalid', 'The token limit desired by the merchant is not within the agreed range between the merchant and the Issuer', 'flyway', 'flyway'),
('BUSINESS', 403, '73', '23', '4037323', 'Account Limit Exceed', 'Account aggregated purchase amount on that day exceeds the agreed limit', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '00', '4047300', 'Invalid Transaction Status', 'Invalid transaction status', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '01', '4047301', 'Transaction Not Found', 'Transaction not found', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '02', '4047302', 'Invalid Routing', 'Invalid Routing', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '03', '4047303', 'Bank Not Supported By Switch', 'Bank not supported by switch', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '04', '4047304', 'Transaction Cancelled', 'Transaction is cancelled by customer', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '05', '4047305', 'Merchant Is Not Registered For Card Registration Services', 'Merchant is not registered for Card Registration services', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '06', '4047306', 'Need To Request OTP', 'Need to request OTP', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '07', '4047307', 'Journey Not Found', 'The journeyId cannot be found in the system', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '08', '4047308', 'Invalid Merchant', 'Merchant does not exist or status abnormal', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '09', '4047309', 'No Issuer', 'No issuer', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '10', '4047310', 'Invalid API Transition', 'Invalid API transition within a journey', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '11', '4047311', 'Invalid Card/Account/Customer [info]/Virtual Account', 'Card information may be invalid, or the card account may be blacklisted, or Virtual Account number maybe invalid.', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '12', '4047312', 'Invalid Bill/Virtual Account [Reason]', 'The bill is blocked/suspended/not found. Virtual account is suspend/not found.', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '13', '4047313', 'Invalid Amount', 'The amount does not match with what supposed to', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '14', '4047314', 'Paid Bill', 'The bill has been paid', 'flyway', 'flyway'),
('SYSTEM', 404, '73', '15', '4047315', 'Invalid OTP', 'OTP is incorrect', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '16', '4047316', 'Partner Not Found', 'Partner number cannot be found', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '17', '4047317', 'Invalid Terminal', 'Terminal does not exist in the system', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '18', '4047318', 'Inconsistent Request', 'Inconsistent request parameter found for the same partner reference number/transaction id. It can be considered as failed in transfer debit, but it should be considered as success in transfer credit. Considered as success: Transfer credit = (i) Intrabank transfer; (ii) Interbank transfer; (iii) RTGS transfer; (iv) SKNBI transfer; Virtual account = (i) Payment VA; (ii) Payment to VA; Transfer debit = (i) Refund payment; (ii) Void. Considered as failed: Transfer credit = (i) Transfer to OTC; Transfer debit = (i) Direct debit payment; (ii) QR CPM payment; (iii) Auth payment; (iv) Capture.', 'flyway', 'flyway'),
('BUSINESS', 404, '73', '19', '4047319', 'Invalid Bill/Virtual Account', 'The bill is expired. Virtual account is expired.', 'flyway', 'flyway'),
('SYSTEM', 405, '73', '00', '4057300', 'Requested Function Is Not Supported', 'Requested function is not supported', 'flyway', 'flyway'),
('BUSINESS', 405, '73', '01', '4057301', 'Requested Opearation Is Not Allowed', 'Requested operation to cancel/refund transaction Is not allowed at this time.', 'flyway', 'flyway'),
('SYSTEM', 409, '73', '00', '4097300', 'Conflict', 'Cannot use same X-EXTERNAL-ID in same day', 'flyway', 'flyway'),
('SYSTEM', 409, '73', '01', '4097301', 'Duplicate partnerReferenceNo', 'Transaction has previously been processed indicates the same partnerReferenceNo already success', 'flyway', 'flyway'),
('SYSTEM', 429, '73', '00', '4297300', 'Too Many Requests', 'Maximum transaction limit exceeded', 'flyway', 'flyway'),
('SYSTEM', 500, '73', '00', '5007300', 'General Error', 'General Error', 'flyway', 'flyway'),
('SYSTEM', 500, '73', '01', '5007301', 'Internal Server Error', 'Unknown Internal Server Failure, Please retry the process again', 'flyway', 'flyway'),
('SYSTEM', 500, '73', '02', '5007302', 'External Server Error', 'Backend system failure, etc', 'flyway', 'flyway'),
('SYSTEM', 504, '73', '00', '5047300', 'Timeout', 'timeout from the issuer', 'flyway', 'flyway');
